name: widget-server pipe

on: 
  push: 
    branches: 
      - 'staging'

jobs:
  Build: 
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
